# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */2 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.22
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          users_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot], actions-user, action@github.com
          plugin_repositories_skipped: Operator2024/Operator2024
          repositories_skipped: Operator2024/Operator2024
          user: Operator2024
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: Asia/Yekaterinburg
          config_twemoji: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: no
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 365
          plugin_activity_filter: all
          plugin_activity_limit: 8
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_activity_ignored: github-actions[bot]
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_skipped: Operator2024/Operator2024
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_indepth: no
          commits_authoring: firstname lastname, username, work.pwnz@gmail.com, work.pwnz+github@gmail.com, Operator2024, Vladimir Belomestnykh
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming, data
          plugin_languages_recent_days: 90
          plugin_languages_recent_load: 600
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0.1%
          plugin_languages_other: false
          repositories_forks: yes
          plugin_lines: yes
          repositories: 100
